upstream_repos:
  - anaconda
  - http://centos.mirror.ndchost.com/7.3.1611/updates/x86_64/
  - http://mirror.hmc.edu/centos/7.3.1611/extras/x86_64/
  - http://mirror.scalabledns.com/centos/7.3.1611/os/x86_64/
  - http://us.archive.ubuntu.com/ubuntu/
